apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdpass-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowdpass
  template:
    metadata:
      labels:
        app: crowdpass
    spec:
      containers:
        - name: crowdpass
          image: crowdpass-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
