apiVersion: v1
kind: Service
metadata:
  name: crowdpass-service
spec:
  type: NodePort
  selector:
    app: crowdpass
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
